"""Add is_admin field to User

Revision ID: 2091f5ea1632
Revises: bc5fae4b70a1
Create Date: 2025-05-10 17:36:45.380888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2091f5ea1632'
down_revision = 'bc5fae4b70a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
