"""Add status field to Report model

Revision ID: 792f403f0f4f
Revises: 2091f5ea1632
Create Date: 2025-05-18 12:27:43.762499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792f403f0f4f'
down_revision = '2091f5ea1632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
