"""Add offender_username and offender_profile fields to Report

Revision ID: bc5fae4b70a1
Revises: 01d411bfe40e
Create Date: 2025-05-10 17:24:24.612188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc5fae4b70a1'
down_revision = '01d411bfe40e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offender_username', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('offender_profile', sa.String(length=300), nullable=True))
        batch_op.drop_column('offender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offender', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('offender_profile')
        batch_op.drop_column('offender_username')

    # ### end Alembic commands ###
